### ISSUE TITLE
小三角边框样式优化

### ISSUE THREAD

**Issue by xuexb** [aui/artDialog#105]
如果使用:

``` css
/*默认8px边框,不显示*/
.a,.b{display:none;border:8px dashed transparent;}

/*有吸附*/
.follow .a,.follow .b{display:block;}

/*控制方向*/
.left .a{top:16px;border-top:8px solid #bab0b8;}/*倍数*/
.left .b{top:15px;border-top:8px solid #fff;}/*-1*/
```
